/** @format */

import {attribute, table, autoGeneratedHashKey, rangeKey} from '@aws/dynamodb-data-mapper-annotations'

@table('taskTable')
export class Task {
  @autoGeneratedHashKey()
  workspace: string

  // editor - Version -  creationDate
  @rangeKey({
    indexKeyConfigurations: {
      ProjectGsiIndex: 'RANGE',
    },
  })
  taskId?: string

  @attribute()
  creator?: string

  @attribute()
  editor: string

  @attribute()
  title: string

  @attribute()
  description?: string

  @attribute({defaultProvider: () => 0})
  priority?: number

  @attribute({
    // BUT, this also acts as the HashKey for your GSI
    indexKeyConfigurations: {
      ProjectGsiIndex: 'HASH',
    },
  })
  project: string

  @attribute()
  parentProject?: string

  @attribute()
  startTime?: string

  @attribute()
  endTime?: string

  @attribute()
  dueDate?: string

  @attribute({defaultProvider: () => 'Not categorized'})
  category?: string

  @attribute()
  doState?: string

  @attribute()
  subTasks?: string[]

  @attribute()
  complexity?: number

  @attribute({defaultProvider: () => new Date()})
  createdAt?: Date
}
